In [6]:
import pandas as pd
from sklearn.decomposition import PCA
import scipy
from scipy import stats
import numpy as np

In [8]:
data = pd.read_table("Nichols_Nicki.dat")
data

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias27  \
0       1     1     2     1     1     1     1     2     2      1  ...      3   
1       2     1     3     1     2     1     1     2     1      1  ...      3   
2       4     2     4     2     3     3     4     2     3      3  ...      3   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      3   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      3   
203     1     1     4     1     1     1     1     3     1      1  ...      2   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      4   
206     1     1     1     1     2     1     3     4     4      3  ...      2   

     ias28  ias29  ias30  ias31  ias32  ias33  ias34  ias35  ias36  
0        1      1      1      1      1      1      1      1      1  
1        1      1      1      2      1      2      1      1      1  
2        2      2      3      3      1      2      2      1      3  
3        1      1      1      2      1      1      1      1      1  
4        1      1      1      2      1      1      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      1      3      4      3      1      1      1      1  
203      1      1      1      2      1      1      1      2      1  
204      2      1      4      2      4      2      1      1      1  
205      3      1      1      4      3      1      1      1      1  
206      3      2      2      2      3      1      1      2      3  

[207 rows x 36 columns]

In [40]:
df = pd.DataFrame(data)
variance = df.var()
sorted_variance = variance.sort_values()
print(sorted_variance.head())
df2 = data.drop(columns=['ias34','ias23'])

ias34    0.118662
ias23    0.182778
ias15    0.266357
ias28    0.317480
ias6     0.319310
dtype: float64


In [43]:
matrix = df2.corr()
print(matrix)

           ias1      ias2      ias3      ias4      ias5      ias6      ias7  \
ias1   1.000000  0.427736  0.462768  0.354683  0.517041  0.558645  0.478892   
ias2   0.427736  1.000000  0.330520  0.541461  0.379329  0.239192  0.394668   
ias3   0.462768  0.330520  1.000000  0.518899  0.474619  0.405834  0.485200   
ias4   0.354683  0.541461  0.518899  1.000000  0.462147  0.266996  0.451263   
ias5   0.517041  0.379329  0.474619  0.462147  1.000000  0.481312  0.429718   
ias6   0.558645  0.239192  0.405834  0.266996  0.481312  1.000000  0.497405   
ias7   0.478892  0.394668  0.485200  0.451263  0.429718  0.497405  1.000000   
ias8   0.476363  0.316346  0.624529  0.444075  0.588049  0.433835  0.465954   
ias9   0.512624  0.285332  0.500271  0.369303  0.508687  0.499149  0.541858   
ias10  0.431542  0.295806  0.401046  0.370661  0.520405  0.587692  0.601882   
ias11  0.418803  0.260113  0.428615  0.266908  0.336068  0.420593  0.407984   
ias12  0.426479  0.317615  0.456818  0.441042  0.437

In [42]:
sums = matrix.sum()
min_corr = sums.nsmallest(3).index
print(min_corr)


Index(['ias13', 'ias22', 'ias32'], dtype='object')


In [45]:
new_df = df2.drop(columns=['ias13','ias22', 'ias32'])
print("5 columns were dropped, 2 due to low variances and 3 due to low correlations.")
print("Columns ias23 and ias34 were dropped for low variances.")
print("Columns ias13, ias22 and ias32 were dropped due to low correlations.")


5 columns were dropped, 2 due to low variances and 3 due to low correlations.
Columns ias23 and ias34 were dropped for low variances.
Columns ias13, ias22 and ias32 were dropped due to low correlations.


In [46]:
new_df

ias1  ias2  ias3  ias4  ias5  ias6  ias7  ias8  ias9  ias10  ...  ias25  \
0       1     1     2     1     1     1     1     2     2      1  ...      1   
1       2     1     3     1     2     1     1     2     1      1  ...      1   
2       4     2     4     2     3     3     4     2     3      3  ...      2   
3       1     1     3     1     1     1     1     2     1      1  ...      1   
4       2     1     3     2     1     1     1     2     3      1  ...      1   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
202     1     1     3     2     2     1     1     2     1      1  ...      2   
203     1     1     4     1     1     1     1     3     1      1  ...      1   
204     3     2     4     3     2     3     2     4     4      2  ...      2   
205     3     1     5     1     1     3     4     3     2      2  ...      1   
206     1     1     1     1     2     1     3     4     4      3  ...      3   

     ias26  ias27  ias28  ias29  ias30  ias31  ias33  ias35  ias36  
0        1      3      1      1      1      1      1      1      1  
1        1      3      1      1      1      2      2      1      1  
2        3      3      2      2      3      3      2      1      3  
3        1      1      1      1      1      2      1      1      1  
4        1      3      1      1      1      2      1      3      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
202      1      3      1      1      3      4      1      1      1  
203      1      2      1      1      1      2      1      2      1  
204      3      2      2      1      4      2      2      1      1  
205      2      4      3      1      1      4      1      1      1  
206      1      2      3      2      2      2      1      2      3  

[207 rows x 31 columns]

In [47]:
cov_mat = np.cov(new_df.T)
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
eigen_vals

array([9.39125543, 1.24515555, 1.10299324, 0.95304005, 0.77301975,
       0.63877591, 0.57708496, 0.53989026, 0.46848507, 0.44204512,
       0.41070427, 0.37201006, 0.36019535, 0.0453143 , 0.05559301,
       0.06549541, 0.32573639, 0.08833419, 0.10109319, 0.30962996,
       0.12344991, 0.13704314, 0.28016405, 0.16390667, 0.16615511,
       0.18382076, 0.19611993, 0.25722439, 0.24472739, 0.22869559,
       0.23002373])

In [48]:
pca = PCA(n_components=None)
data_pca = pca.fit_transform(new_df)
pca.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ,
       0.03119452, 0.02818185, 0.02636546, 0.0228784 , 0.0215872 ,
       0.02005668, 0.01816705, 0.01759008, 0.01590729, 0.01512073,
       0.01368177, 0.01256151, 0.01195122, 0.01123317, 0.01116831,
       0.00957749, 0.00897686, 0.00811416, 0.00800436, 0.00669248,
       0.00602866, 0.00493687, 0.00431379, 0.00319846, 0.00271488,
       0.00221292])

In [49]:
pca5 = PCA(n_components=5)
data_pca_2 = pca5.fit_transform(new_df)
pca5.explained_variance_ratio_

array([0.4586205 , 0.06080698, 0.0538645 , 0.04654156, 0.0377503 ])