In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/My Drive/ColabData

/content/drive/My Drive/ColabData


In [3]:
import pandas as pd

In [4]:
raq = pd.read_table('raq.dat')

In [5]:
raq

Q01  Q02  Q03  Q04  Q05  Q06  Q07  Q08  Q09  Q10  ...  Q14  Q15  Q16  \
0       4    5    2    4    4    4    3    5    5    4  ...    4    4    3   
1       5    5    2    3    4    4    4    4    1    4  ...    3    2    3   
2       4    3    4    4    2    5    4    4    4    4  ...    2    4    3   
3       3    5    5    2    3    3    2    4    4    2  ...    3    3    3   
4       4    5    3    4    4    3    3    4    2    4  ...    4    4    4   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2566    3    5    4    4    4    5    4    3    4    4  ...    3    3    3   
2567    3    5    4    3    2    2    2    3    4    5  ...    2    2    1   
2568    3    5    4    3    3    4    4    4    5    2  ...    4    4    3   
2569    3    5    3    4    2    4    3    2    5    3  ...    3    3    3   
2570    3    5    2    4    3    4    3    4    4    5  ...    3    3    3   

      Q17  Q18  Q19  Q20  Q21  Q22  Q23  
0       5    4    3    4    4    4    1  
1       4    4    3    2    2    2    4  
2       4    3    5    2    3    4    4  
3       4    2    4    2    2    2    3  
4       4    3    3    2    4    2    2  
...   ...  ...  ...  ...  ...  ...  ...  
2566    3    4    4    3    3    4    2  
2567    1    3    5    1    2    3    5  
2568    4    4    4    2    3    4    2  
2569    3    4    4    2    2    4    3  
2570    3    4    4    4    3    2    2  

[2571 rows x 23 columns]

In [6]:
from sklearn.decomposition import PCA

In [7]:
#Barlett's test
import scipy
from scipy import stats
scipy.stats.bartlett(*raq.values)

BartlettResult(statistic=6544.728590738065, pvalue=0.0)

In [8]:
import numpy as np

In [9]:
cov_mat = np.cov(raq.T)

In [10]:
cov_mat

array([[ 0.68562067, -0.06957201, -0.2996619 ,  0.34233284,  0.32146298,
         0.20135513,  0.27873074,  0.23896045, -0.09657645,  0.15519329,
         0.26013315,  0.26209684,  0.27853293,  0.27937244,  0.2054001 ,
         0.3782077 ,  0.27120305,  0.30270754, -0.17237521,  0.18344419,
         0.26838048, -0.08997589, -0.00387228],
       [-0.06957201,  0.72433503,  0.29130091, -0.0903031 , -0.09798682,
        -0.07086373, -0.14933674, -0.03685102,  0.33824111, -0.06270887,
        -0.10778649, -0.15199691, -0.11522731, -0.13997249, -0.14174351,
        -0.13062927, -0.06544411, -0.14690525,  0.19056689, -0.1777066 ,
        -0.17148379,  0.20450036,  0.08854418],
       [-0.2996619 ,  0.29130091,  1.15564596, -0.38795469, -0.32180623,
        -0.27348607, -0.45263285, -0.24260451,  0.40709076, -0.18235058,
        -0.33190904, -0.40389256, -0.32416674, -0.39799636, -0.33898421,
        -0.4122699 , -0.3110702 , -0.4248322 ,  0.40442923, -0.36168382,
        -0.44162637,  0.2278

In [13]:
#Calculating the eigen value
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)

In [14]:
eigen_vals

array([7.04574432, 1.99272935, 1.3761048 , 1.14200859, 1.04577832,
       0.89325413, 0.85339344, 0.81392445, 0.26008584, 0.30979483,
       0.32175511, 0.74924395, 0.70570257, 0.68971486, 0.37958597,
       0.41783888, 0.44519201, 0.61975491, 0.47977139, 0.49955344,
       0.53111497, 0.56262446, 0.55023906])

In [15]:
pca = PCA(n_components=None)

In [16]:
raq_pca = pca.fit_transform(raq)

In [17]:
pca.explained_variance_ratio_

array([0.31059169, 0.08784383, 0.06066168, 0.05034221, 0.04610018,
       0.03937658, 0.03761943, 0.03587955, 0.0330283 , 0.0311089 ,
       0.03040413, 0.02732014, 0.02480171, 0.02425573, 0.0234127 ,
       0.0220214 , 0.02114936, 0.01962503, 0.01841924, 0.01673297,
       0.01418366, 0.01365643, 0.01146515])

In [18]:
pca = PCA(n_components=5)

In [19]:
raq_pca2 = pca.fit_transform(raq)

In [20]:
pca.explained_variance_ratio_


array([0.31059169, 0.08784308, 0.06065622, 0.05034141, 0.04609719])

In [21]:
raq_pca2

array([[-2.82222283, -1.69964252,  1.77175719,  1.51511356,  1.40198731],
       [-1.65180452,  1.14756903, -0.48546184, -0.73683694, -1.18827933],
       [ 0.14298659, -1.7080261 , -0.62290869, -1.06550575, -0.86610224],
       ...,
       [ 0.16699866, -2.02790902, -0.21344427,  0.39969962,  1.22926456],
       [ 1.09076547, -1.39354459, -0.38523887, -1.40012608,  1.11350842],
       [-1.0454193 ,  0.05315715,  0.28618775, -0.0613747 ,  1.2823724 ]])

In [22]:
pca = PCA(n_components=2)

In [23]:
raq_pca3 = pca.fit_transform(raq)

In [24]:
raq_pca3

array([[-2.82221895, -1.69898327],
       [-1.65175003,  1.14803183],
       [ 0.14293817, -1.70650921],
       ...,
       [ 0.1670029 , -2.03127054],
       [ 1.0908144 , -1.39981707],
       [-1.04536872,  0.05055112]])

In [25]:
raq_pca3_dataframe = pd.DataFrame(data = raq_pca3
             , columns = ['principal component 1', 'principal component 2'])

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(16,10))
sns.scatterplot(
    x="principal component 1", y="principal component 2",
    data=raq_pca3_dataframe,
    legend="full",
    alpha=0.3
)

<Axes: xlabel='principal component 1', ylabel='principal component 2'>